// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetMeIPXEScript
    {
        /// <summary>
        /// Use this data source to retrieve information about an IPXE Script.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var script = Output.Create(Ovh.GetMeIPXEScript.InvokeAsync(new Ovh.GetMeIPXEScriptArgs
        ///         {
        ///             Name = "myscript",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetMeIPXEScriptResult> InvokeAsync(GetMeIPXEScriptArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetMeIPXEScriptResult>("ovh:index/getMeIPXEScript:getMeIPXEScript", args ?? new GetMeIPXEScriptArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about an IPXE Script.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var script = Output.Create(Ovh.GetMeIPXEScript.InvokeAsync(new Ovh.GetMeIPXEScriptArgs
        ///         {
        ///             Name = "myscript",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetMeIPXEScriptResult> Invoke(GetMeIPXEScriptInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetMeIPXEScriptResult>("ovh:index/getMeIPXEScript:getMeIPXEScript", args ?? new GetMeIPXEScriptInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetMeIPXEScriptArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the IPXE Script.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetMeIPXEScriptArgs()
        {
        }
    }

    public sealed class GetMeIPXEScriptInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the IPXE Script.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetMeIPXEScriptInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetMeIPXEScriptResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// See Argument Reference above.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The content of the script.
        /// </summary>
        public readonly string Script;

        [OutputConstructor]
        private GetMeIPXEScriptResult(
            string id,

            string name,

            string script)
        {
            Id = id;
            Name = name;
            Script = script;
        }
    }
}
