// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    /// <summary>
    /// Manage http route for a loadbalancer service
    /// 
    /// ## Example Usage
    /// 
    /// Route which redirect all url to https.
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Ovh = Pulumi.Ovh;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var httpsredirect = new Ovh.IPLoadbalancingHTTPRoute("httpsredirect", new Ovh.IPLoadbalancingHTTPRouteArgs
    ///         {
    ///             Action = new Ovh.Inputs.IPLoadbalancingHTTPRouteActionArgs
    ///             {
    ///                 Status = 302,
    ///                 Target = $"https://{host}{path}{arguments}",
    ///                 Type = "redirect",
    ///             },
    ///             DisplayName = "Redirect to HTTPS",
    ///             ServiceName = "loadbalancer-xxxxxxxxxxxxxxxxxx",
    ///             Weight = 1,
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// </summary>
    [OvhResourceType("ovh:index/iPLoadbalancingHTTPRoute:IPLoadbalancingHTTPRoute")]
    public partial class IPLoadbalancingHTTPRoute : Pulumi.CustomResource
    {
        [Output("action")]
        public Output<Outputs.IPLoadbalancingHTTPRouteAction> Action { get; private set; } = null!;

        /// <summary>
        /// Human readable name for your route, this field is for you
        /// </summary>
        [Output("displayName")]
        public Output<string?> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Route traffic for this frontend
        /// </summary>
        [Output("frontendId")]
        public Output<int> FrontendId { get; private set; } = null!;

        /// <summary>
        /// The internal name of your IP load balancing
        /// </summary>
        [Output("serviceName")]
        public Output<string> ServiceName { get; private set; } = null!;

        /// <summary>
        /// Route priority ([0..255]). 0 if null. Highest priority routes are evaluated first. Only the first matching route will trigger an action
        /// * `action.status` - HTTP status code for "redirect" and "reject" actions
        /// * `action.target` - Farm ID for "farm" action type or URL template for "redirect" action. You may use ${uri}, ${protocol}, ${host}, ${port} and ${path} variables in redirect target
        /// * `action.type` - (Required) Action to trigger if all the rules of this route matches
        /// </summary>
        [Output("weight")]
        public Output<int?> Weight { get; private set; } = null!;


        /// <summary>
        /// Create a IPLoadbalancingHTTPRoute resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IPLoadbalancingHTTPRoute(string name, IPLoadbalancingHTTPRouteArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/iPLoadbalancingHTTPRoute:IPLoadbalancingHTTPRoute", name, args ?? new IPLoadbalancingHTTPRouteArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IPLoadbalancingHTTPRoute(string name, Input<string> id, IPLoadbalancingHTTPRouteState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/iPLoadbalancingHTTPRoute:IPLoadbalancingHTTPRoute", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IPLoadbalancingHTTPRoute resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IPLoadbalancingHTTPRoute Get(string name, Input<string> id, IPLoadbalancingHTTPRouteState? state = null, CustomResourceOptions? options = null)
        {
            return new IPLoadbalancingHTTPRoute(name, id, state, options);
        }
    }

    public sealed class IPLoadbalancingHTTPRouteArgs : Pulumi.ResourceArgs
    {
        [Input("action", required: true)]
        public Input<Inputs.IPLoadbalancingHTTPRouteActionArgs> Action { get; set; } = null!;

        /// <summary>
        /// Human readable name for your route, this field is for you
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Route traffic for this frontend
        /// </summary>
        [Input("frontendId")]
        public Input<int>? FrontendId { get; set; }

        /// <summary>
        /// The internal name of your IP load balancing
        /// </summary>
        [Input("serviceName", required: true)]
        public Input<string> ServiceName { get; set; } = null!;

        /// <summary>
        /// Route priority ([0..255]). 0 if null. Highest priority routes are evaluated first. Only the first matching route will trigger an action
        /// * `action.status` - HTTP status code for "redirect" and "reject" actions
        /// * `action.target` - Farm ID for "farm" action type or URL template for "redirect" action. You may use ${uri}, ${protocol}, ${host}, ${port} and ${path} variables in redirect target
        /// * `action.type` - (Required) Action to trigger if all the rules of this route matches
        /// </summary>
        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public IPLoadbalancingHTTPRouteArgs()
        {
        }
    }

    public sealed class IPLoadbalancingHTTPRouteState : Pulumi.ResourceArgs
    {
        [Input("action")]
        public Input<Inputs.IPLoadbalancingHTTPRouteActionGetArgs>? Action { get; set; }

        /// <summary>
        /// Human readable name for your route, this field is for you
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Route traffic for this frontend
        /// </summary>
        [Input("frontendId")]
        public Input<int>? FrontendId { get; set; }

        /// <summary>
        /// The internal name of your IP load balancing
        /// </summary>
        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        /// <summary>
        /// Route priority ([0..255]). 0 if null. Highest priority routes are evaluated first. Only the first matching route will trigger an action
        /// * `action.status` - HTTP status code for "redirect" and "reject" actions
        /// * `action.target` - Farm ID for "farm" action type or URL template for "redirect" action. You may use ${uri}, ${protocol}, ${host}, ${port} and ${path} variables in redirect target
        /// * `action.type` - (Required) Action to trigger if all the rules of this route matches
        /// </summary>
        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public IPLoadbalancingHTTPRouteState()
        {
        }
    }
}
