// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    /// <summary>
    /// Creates an SSH Key.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Ovh = Pulumi.Ovh;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var mykey = new Ovh.MeSSHKey("mykey", new Ovh.MeSSHKeyArgs
    ///         {
    ///             Key = "ssh-ed25519 AAAAC3...",
    ///             KeyName = "mykey",
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// </summary>
    [OvhResourceType("ovh:index/meSSHKey:MeSSHKey")]
    public partial class MeSSHKey : Pulumi.CustomResource
    {
        /// <summary>
        /// True when this public SSH key is used for rescue mode and reinstallations.
        /// </summary>
        [Output("default")]
        public Output<bool> Default { get; private set; } = null!;

        /// <summary>
        /// The content of the public key in the form "ssh-algo content", e.g. "ssh-ed25519 AAAAC3...".
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// The friendly name of this SSH key.
        /// </summary>
        [Output("keyName")]
        public Output<string> KeyName { get; private set; } = null!;


        /// <summary>
        /// Create a MeSSHKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MeSSHKey(string name, MeSSHKeyArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/meSSHKey:MeSSHKey", name, args ?? new MeSSHKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MeSSHKey(string name, Input<string> id, MeSSHKeyState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/meSSHKey:MeSSHKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MeSSHKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MeSSHKey Get(string name, Input<string> id, MeSSHKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new MeSSHKey(name, id, state, options);
        }
    }

    public sealed class MeSSHKeyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// True when this public SSH key is used for rescue mode and reinstallations.
        /// </summary>
        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// The content of the public key in the form "ssh-algo content", e.g. "ssh-ed25519 AAAAC3...".
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The friendly name of this SSH key.
        /// </summary>
        [Input("keyName", required: true)]
        public Input<string> KeyName { get; set; } = null!;

        public MeSSHKeyArgs()
        {
        }
    }

    public sealed class MeSSHKeyState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// True when this public SSH key is used for rescue mode and reinstallations.
        /// </summary>
        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// The content of the public key in the form "ssh-algo content", e.g. "ssh-ed25519 AAAAC3...".
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The friendly name of this SSH key.
        /// </summary>
        [Input("keyName")]
        public Input<string>? KeyName { get; set; }

        public MeSSHKeyState()
        {
        }
    }
}
