// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a private network in a public cloud project.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-ovh/sdk/go/ovh"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := ovh.NewCloudNetworkPrivate(ctx, "net", &ovh.CloudNetworkPrivateArgs{
// 			ProjectId: pulumi.String("67890"),
// 			Regions: pulumi.StringArray{
// 				pulumi.String("GRA1"),
// 				pulumi.String("BHS1"),
// 			},
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
type CloudNetworkPrivate struct {
	pulumi.CustomResourceState

	// The name of the network.
	Name pulumi.StringOutput `pulumi:"name"`
	// The id of the public cloud project. If omitted,
	// the `OVH_PROJECT_ID` environment variable is used.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// an array of valid OVH public cloud region ID in which the network
	// will be available. Ex.: "GRA1". Defaults to all public cloud regions.
	Regions pulumi.StringArrayOutput `pulumi:"regions"`
	// A map representing the status of the network per region.
	// * `regions_status/region` - The id of the region.
	// * `regions_status/status` - The status of the network in the region.
	RegionsStatuses CloudNetworkPrivateRegionsStatusArrayOutput `pulumi:"regionsStatuses"`
	// the status of the network. should be normally set to 'ACTIVE'.
	Status pulumi.StringOutput `pulumi:"status"`
	// the type of the network. Either 'private' or 'public'.
	Type pulumi.StringOutput `pulumi:"type"`
	// a vlan id to associate with the network.
	// Changing this value recreates the resource. Defaults to 0.
	VlanId pulumi.IntPtrOutput `pulumi:"vlanId"`
}

// NewCloudNetworkPrivate registers a new resource with the given unique name, arguments, and options.
func NewCloudNetworkPrivate(ctx *pulumi.Context,
	name string, args *CloudNetworkPrivateArgs, opts ...pulumi.ResourceOption) (*CloudNetworkPrivate, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	var resource CloudNetworkPrivate
	err := ctx.RegisterResource("ovh:index/cloudNetworkPrivate:CloudNetworkPrivate", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudNetworkPrivate gets an existing CloudNetworkPrivate resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudNetworkPrivate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudNetworkPrivateState, opts ...pulumi.ResourceOption) (*CloudNetworkPrivate, error) {
	var resource CloudNetworkPrivate
	err := ctx.ReadResource("ovh:index/cloudNetworkPrivate:CloudNetworkPrivate", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudNetworkPrivate resources.
type cloudNetworkPrivateState struct {
	// The name of the network.
	Name *string `pulumi:"name"`
	// The id of the public cloud project. If omitted,
	// the `OVH_PROJECT_ID` environment variable is used.
	ProjectId *string `pulumi:"projectId"`
	// an array of valid OVH public cloud region ID in which the network
	// will be available. Ex.: "GRA1". Defaults to all public cloud regions.
	Regions []string `pulumi:"regions"`
	// A map representing the status of the network per region.
	// * `regions_status/region` - The id of the region.
	// * `regions_status/status` - The status of the network in the region.
	RegionsStatuses []CloudNetworkPrivateRegionsStatus `pulumi:"regionsStatuses"`
	// the status of the network. should be normally set to 'ACTIVE'.
	Status *string `pulumi:"status"`
	// the type of the network. Either 'private' or 'public'.
	Type *string `pulumi:"type"`
	// a vlan id to associate with the network.
	// Changing this value recreates the resource. Defaults to 0.
	VlanId *int `pulumi:"vlanId"`
}

type CloudNetworkPrivateState struct {
	// The name of the network.
	Name pulumi.StringPtrInput
	// The id of the public cloud project. If omitted,
	// the `OVH_PROJECT_ID` environment variable is used.
	ProjectId pulumi.StringPtrInput
	// an array of valid OVH public cloud region ID in which the network
	// will be available. Ex.: "GRA1". Defaults to all public cloud regions.
	Regions pulumi.StringArrayInput
	// A map representing the status of the network per region.
	// * `regions_status/region` - The id of the region.
	// * `regions_status/status` - The status of the network in the region.
	RegionsStatuses CloudNetworkPrivateRegionsStatusArrayInput
	// the status of the network. should be normally set to 'ACTIVE'.
	Status pulumi.StringPtrInput
	// the type of the network. Either 'private' or 'public'.
	Type pulumi.StringPtrInput
	// a vlan id to associate with the network.
	// Changing this value recreates the resource. Defaults to 0.
	VlanId pulumi.IntPtrInput
}

func (CloudNetworkPrivateState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudNetworkPrivateState)(nil)).Elem()
}

type cloudNetworkPrivateArgs struct {
	// The name of the network.
	Name *string `pulumi:"name"`
	// The id of the public cloud project. If omitted,
	// the `OVH_PROJECT_ID` environment variable is used.
	ProjectId string `pulumi:"projectId"`
	// an array of valid OVH public cloud region ID in which the network
	// will be available. Ex.: "GRA1". Defaults to all public cloud regions.
	Regions []string `pulumi:"regions"`
	// a vlan id to associate with the network.
	// Changing this value recreates the resource. Defaults to 0.
	VlanId *int `pulumi:"vlanId"`
}

// The set of arguments for constructing a CloudNetworkPrivate resource.
type CloudNetworkPrivateArgs struct {
	// The name of the network.
	Name pulumi.StringPtrInput
	// The id of the public cloud project. If omitted,
	// the `OVH_PROJECT_ID` environment variable is used.
	ProjectId pulumi.StringInput
	// an array of valid OVH public cloud region ID in which the network
	// will be available. Ex.: "GRA1". Defaults to all public cloud regions.
	Regions pulumi.StringArrayInput
	// a vlan id to associate with the network.
	// Changing this value recreates the resource. Defaults to 0.
	VlanId pulumi.IntPtrInput
}

func (CloudNetworkPrivateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudNetworkPrivateArgs)(nil)).Elem()
}

type CloudNetworkPrivateInput interface {
	pulumi.Input

	ToCloudNetworkPrivateOutput() CloudNetworkPrivateOutput
	ToCloudNetworkPrivateOutputWithContext(ctx context.Context) CloudNetworkPrivateOutput
}

func (*CloudNetworkPrivate) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudNetworkPrivate)(nil)).Elem()
}

func (i *CloudNetworkPrivate) ToCloudNetworkPrivateOutput() CloudNetworkPrivateOutput {
	return i.ToCloudNetworkPrivateOutputWithContext(context.Background())
}

func (i *CloudNetworkPrivate) ToCloudNetworkPrivateOutputWithContext(ctx context.Context) CloudNetworkPrivateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudNetworkPrivateOutput)
}

// CloudNetworkPrivateArrayInput is an input type that accepts CloudNetworkPrivateArray and CloudNetworkPrivateArrayOutput values.
// You can construct a concrete instance of `CloudNetworkPrivateArrayInput` via:
//
//          CloudNetworkPrivateArray{ CloudNetworkPrivateArgs{...} }
type CloudNetworkPrivateArrayInput interface {
	pulumi.Input

	ToCloudNetworkPrivateArrayOutput() CloudNetworkPrivateArrayOutput
	ToCloudNetworkPrivateArrayOutputWithContext(context.Context) CloudNetworkPrivateArrayOutput
}

type CloudNetworkPrivateArray []CloudNetworkPrivateInput

func (CloudNetworkPrivateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudNetworkPrivate)(nil)).Elem()
}

func (i CloudNetworkPrivateArray) ToCloudNetworkPrivateArrayOutput() CloudNetworkPrivateArrayOutput {
	return i.ToCloudNetworkPrivateArrayOutputWithContext(context.Background())
}

func (i CloudNetworkPrivateArray) ToCloudNetworkPrivateArrayOutputWithContext(ctx context.Context) CloudNetworkPrivateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudNetworkPrivateArrayOutput)
}

// CloudNetworkPrivateMapInput is an input type that accepts CloudNetworkPrivateMap and CloudNetworkPrivateMapOutput values.
// You can construct a concrete instance of `CloudNetworkPrivateMapInput` via:
//
//          CloudNetworkPrivateMap{ "key": CloudNetworkPrivateArgs{...} }
type CloudNetworkPrivateMapInput interface {
	pulumi.Input

	ToCloudNetworkPrivateMapOutput() CloudNetworkPrivateMapOutput
	ToCloudNetworkPrivateMapOutputWithContext(context.Context) CloudNetworkPrivateMapOutput
}

type CloudNetworkPrivateMap map[string]CloudNetworkPrivateInput

func (CloudNetworkPrivateMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudNetworkPrivate)(nil)).Elem()
}

func (i CloudNetworkPrivateMap) ToCloudNetworkPrivateMapOutput() CloudNetworkPrivateMapOutput {
	return i.ToCloudNetworkPrivateMapOutputWithContext(context.Background())
}

func (i CloudNetworkPrivateMap) ToCloudNetworkPrivateMapOutputWithContext(ctx context.Context) CloudNetworkPrivateMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudNetworkPrivateMapOutput)
}

type CloudNetworkPrivateOutput struct{ *pulumi.OutputState }

func (CloudNetworkPrivateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudNetworkPrivate)(nil)).Elem()
}

func (o CloudNetworkPrivateOutput) ToCloudNetworkPrivateOutput() CloudNetworkPrivateOutput {
	return o
}

func (o CloudNetworkPrivateOutput) ToCloudNetworkPrivateOutputWithContext(ctx context.Context) CloudNetworkPrivateOutput {
	return o
}

type CloudNetworkPrivateArrayOutput struct{ *pulumi.OutputState }

func (CloudNetworkPrivateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudNetworkPrivate)(nil)).Elem()
}

func (o CloudNetworkPrivateArrayOutput) ToCloudNetworkPrivateArrayOutput() CloudNetworkPrivateArrayOutput {
	return o
}

func (o CloudNetworkPrivateArrayOutput) ToCloudNetworkPrivateArrayOutputWithContext(ctx context.Context) CloudNetworkPrivateArrayOutput {
	return o
}

func (o CloudNetworkPrivateArrayOutput) Index(i pulumi.IntInput) CloudNetworkPrivateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CloudNetworkPrivate {
		return vs[0].([]*CloudNetworkPrivate)[vs[1].(int)]
	}).(CloudNetworkPrivateOutput)
}

type CloudNetworkPrivateMapOutput struct{ *pulumi.OutputState }

func (CloudNetworkPrivateMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudNetworkPrivate)(nil)).Elem()
}

func (o CloudNetworkPrivateMapOutput) ToCloudNetworkPrivateMapOutput() CloudNetworkPrivateMapOutput {
	return o
}

func (o CloudNetworkPrivateMapOutput) ToCloudNetworkPrivateMapOutputWithContext(ctx context.Context) CloudNetworkPrivateMapOutput {
	return o
}

func (o CloudNetworkPrivateMapOutput) MapIndex(k pulumi.StringInput) CloudNetworkPrivateOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CloudNetworkPrivate {
		return vs[0].(map[string]*CloudNetworkPrivate)[vs[1].(string)]
	}).(CloudNetworkPrivateOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudNetworkPrivateInput)(nil)).Elem(), &CloudNetworkPrivate{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudNetworkPrivateArrayInput)(nil)).Elem(), CloudNetworkPrivateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudNetworkPrivateMapInput)(nil)).Elem(), CloudNetworkPrivateMap{})
	pulumi.RegisterOutputType(CloudNetworkPrivateOutput{})
	pulumi.RegisterOutputType(CloudNetworkPrivateArrayOutput{})
	pulumi.RegisterOutputType(CloudNetworkPrivateMapOutput{})
}
