// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// > __DEPRECATED:__ Use `getCloudRegions` instead.
//
// Use this data source to get the regions of a public cloud project.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-ovh/sdk/go/ovh"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := ovh.GetPublicCloudRegions(ctx, &GetPublicCloudRegionsArgs{
// 			HasServicesUps: []string{
// 				"network",
// 			},
// 			ProjectId: "XXXXXX",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetPublicCloudRegions(ctx *pulumi.Context, args *GetPublicCloudRegionsArgs, opts ...pulumi.InvokeOption) (*GetPublicCloudRegionsResult, error) {
	var rv GetPublicCloudRegionsResult
	err := ctx.Invoke("ovh:index/getPublicCloudRegions:getPublicCloudRegions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPublicCloudRegions.
type GetPublicCloudRegionsArgs struct {
	// List of services which has to be UP in regions.
	// Example: "image", "instance", "network", "storage", "volume", "workflow", ...
	// If left blank, returns all regions associated with the project_id.
	HasServicesUps []string `pulumi:"hasServicesUps"`
	// The id of the public cloud project. If omitted,
	// the `OVH_PROJECT_ID` environment variable is used.
	ProjectId string `pulumi:"projectId"`
}

// A collection of values returned by getPublicCloudRegions.
type GetPublicCloudRegionsResult struct {
	HasServicesUps []string `pulumi:"hasServicesUps"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The list of regions associated with the project, filtered by services UP.
	Names     []string `pulumi:"names"`
	ProjectId string   `pulumi:"projectId"`
}

func GetPublicCloudRegionsOutput(ctx *pulumi.Context, args GetPublicCloudRegionsOutputArgs, opts ...pulumi.InvokeOption) GetPublicCloudRegionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetPublicCloudRegionsResult, error) {
			args := v.(GetPublicCloudRegionsArgs)
			r, err := GetPublicCloudRegions(ctx, &args, opts...)
			return *r, err
		}).(GetPublicCloudRegionsResultOutput)
}

// A collection of arguments for invoking getPublicCloudRegions.
type GetPublicCloudRegionsOutputArgs struct {
	// List of services which has to be UP in regions.
	// Example: "image", "instance", "network", "storage", "volume", "workflow", ...
	// If left blank, returns all regions associated with the project_id.
	HasServicesUps pulumi.StringArrayInput `pulumi:"hasServicesUps"`
	// The id of the public cloud project. If omitted,
	// the `OVH_PROJECT_ID` environment variable is used.
	ProjectId pulumi.StringInput `pulumi:"projectId"`
}

func (GetPublicCloudRegionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPublicCloudRegionsArgs)(nil)).Elem()
}

// A collection of values returned by getPublicCloudRegions.
type GetPublicCloudRegionsResultOutput struct{ *pulumi.OutputState }

func (GetPublicCloudRegionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPublicCloudRegionsResult)(nil)).Elem()
}

func (o GetPublicCloudRegionsResultOutput) ToGetPublicCloudRegionsResultOutput() GetPublicCloudRegionsResultOutput {
	return o
}

func (o GetPublicCloudRegionsResultOutput) ToGetPublicCloudRegionsResultOutputWithContext(ctx context.Context) GetPublicCloudRegionsResultOutput {
	return o
}

func (o GetPublicCloudRegionsResultOutput) HasServicesUps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPublicCloudRegionsResult) []string { return v.HasServicesUps }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetPublicCloudRegionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPublicCloudRegionsResult) string { return v.Id }).(pulumi.StringOutput)
}

// The list of regions associated with the project, filtered by services UP.
func (o GetPublicCloudRegionsResultOutput) Names() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPublicCloudRegionsResult) []string { return v.Names }).(pulumi.StringArrayOutput)
}

func (o GetPublicCloudRegionsResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPublicCloudRegionsResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPublicCloudRegionsResultOutput{})
}
