# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .cloud_network_private import *
from .cloud_network_private_subnet import *
from .cloud_user import *
from .dedicated_ceph_acl import *
from .dedicated_server_install_task import *
from .dedicated_server_reboot_task import *
from .dedicated_server_update import *
from .domain_zone_record import *
from .domain_zone_redirection import *
from .get_cloud_region import *
from .get_cloud_regions import *
from .get_dedicated_ceph import *
from .get_dedicated_installation_templates import *
from .get_dedicated_server import *
from .get_dedicated_server_boots import *
from .get_dedicated_servers import *
from .get_domain_zone import *
from .get_ip_loadbalancing import *
from .get_ip_loadbalancing_vrac_network import *
from .get_ip_loadbalancing_vrac_networks import *
from .get_me_installation_template import *
from .get_me_installation_templates import *
from .get_me_ipxe_script import *
from .get_me_ipxe_scripts import *
from .get_me_payment_mean_bank_account import *
from .get_me_payment_mean_credit_card import *
from .get_me_ssh_key import *
from .get_me_ssh_keys import *
from .get_public_cloud_region import *
from .get_public_cloud_regions import *
from .get_vps import *
from .get_vracks import *
from .ip_loadbalancing_http_farm import *
from .ip_loadbalancing_http_farm_server import *
from .ip_loadbalancing_http_frontend import *
from .ip_loadbalancing_http_route import *
from .ip_loadbalancing_http_route_rule import *
from .ip_loadbalancing_refresh import *
from .ip_loadbalancing_tcp_farm import *
from .ip_loadbalancing_tcp_farm_server import *
from .ip_loadbalancing_tcp_frontend import *
from .ip_loadbalancing_vrac_network import *
from .ip_reverse import *
from .me_installation_template import *
from .me_installation_template_partition_scheme import *
from .me_installation_template_partition_scheme_hardware_raid import *
from .me_installation_template_partition_scheme_partition import *
from .me_ipxe_script import *
from .me_ssh_key import *
from .provider import *
from .pubic_cloud_private_network import *
from .pubic_cloud_private_network_subnet import *
from .public_cloud_user import *
from .vrac_cloud_project import *
from .vrac_dedicated_server import *
from .vrac_dedicated_server_interface import *
from .vrac_public_cloud_attachment import *
from .vracip_loadbalancing import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_ovh.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_ovh.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ovh",
  "mod": "index/cloudNetworkPrivate",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/cloudNetworkPrivate:CloudNetworkPrivate": "CloudNetworkPrivate"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/cloudNetworkPrivateSubnet",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/cloudNetworkPrivateSubnet:CloudNetworkPrivateSubnet": "CloudNetworkPrivateSubnet"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/cloudUser",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/cloudUser:CloudUser": "CloudUser"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/dedicatedCephACL",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/dedicatedCephACL:DedicatedCephACL": "DedicatedCephACL"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/dedicatedServerInstallTask",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/dedicatedServerInstallTask:DedicatedServerInstallTask": "DedicatedServerInstallTask"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/dedicatedServerRebootTask",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/dedicatedServerRebootTask:DedicatedServerRebootTask": "DedicatedServerRebootTask"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/dedicatedServerUpdate",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/dedicatedServerUpdate:DedicatedServerUpdate": "DedicatedServerUpdate"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/domainZoneRecord",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/domainZoneRecord:DomainZoneRecord": "DomainZoneRecord"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/domainZoneRedirection",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/domainZoneRedirection:DomainZoneRedirection": "DomainZoneRedirection"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingHTTPFarm",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingHTTPFarm:IPLoadbalancingHTTPFarm": "IPLoadbalancingHTTPFarm"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingHTTPFarmServer",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingHTTPFarmServer:IPLoadbalancingHTTPFarmServer": "IPLoadbalancingHTTPFarmServer"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingHTTPFrontend",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingHTTPFrontend:IPLoadbalancingHTTPFrontend": "IPLoadbalancingHTTPFrontend"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingHTTPRoute",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingHTTPRoute:IPLoadbalancingHTTPRoute": "IPLoadbalancingHTTPRoute"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingHTTPRouteRule",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingHTTPRouteRule:IPLoadbalancingHTTPRouteRule": "IPLoadbalancingHTTPRouteRule"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingRefresh",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingRefresh:IPLoadbalancingRefresh": "IPLoadbalancingRefresh"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingTCPFarm",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingTCPFarm:IPLoadbalancingTCPFarm": "IPLoadbalancingTCPFarm"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingTCPFarmServer",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingTCPFarmServer:IPLoadbalancingTCPFarmServer": "IPLoadbalancingTCPFarmServer"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingTCPFrontend",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingTCPFrontend:IPLoadbalancingTCPFrontend": "IPLoadbalancingTCPFrontend"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPLoadbalancingVRACNetwork",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPLoadbalancingVRACNetwork:IPLoadbalancingVRACNetwork": "IPLoadbalancingVRACNetwork"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/iPReverse",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/iPReverse:IPReverse": "IPReverse"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/meIPXEScript",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/meIPXEScript:MeIPXEScript": "MeIPXEScript"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/meInstallationTemplate",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/meInstallationTemplate:MeInstallationTemplate": "MeInstallationTemplate"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/meInstallationTemplatePartitionScheme",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/meInstallationTemplatePartitionScheme:MeInstallationTemplatePartitionScheme": "MeInstallationTemplatePartitionScheme"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/meInstallationTemplatePartitionSchemeHardwareRaid",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/meInstallationTemplatePartitionSchemeHardwareRaid:MeInstallationTemplatePartitionSchemeHardwareRaid": "MeInstallationTemplatePartitionSchemeHardwareRaid"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/meInstallationTemplatePartitionSchemePartition",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/meInstallationTemplatePartitionSchemePartition:MeInstallationTemplatePartitionSchemePartition": "MeInstallationTemplatePartitionSchemePartition"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/meSSHKey",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/meSSHKey:MeSSHKey": "MeSSHKey"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/pubicCloudPrivateNetwork",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/pubicCloudPrivateNetwork:PubicCloudPrivateNetwork": "PubicCloudPrivateNetwork"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/pubicCloudPrivateNetworkSubnet",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/pubicCloudPrivateNetworkSubnet:PubicCloudPrivateNetworkSubnet": "PubicCloudPrivateNetworkSubnet"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/publicCloudUser",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/publicCloudUser:PublicCloudUser": "PublicCloudUser"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/vRACCloudProject",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/vRACCloudProject:VRACCloudProject": "VRACCloudProject"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/vRACDedicatedServer",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/vRACDedicatedServer:VRACDedicatedServer": "VRACDedicatedServer"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/vRACDedicatedServerInterface",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/vRACDedicatedServerInterface:VRACDedicatedServerInterface": "VRACDedicatedServerInterface"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/vRACIPLoadbalancing",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/vRACIPLoadbalancing:VRACIPLoadbalancing": "VRACIPLoadbalancing"
  }
 },
 {
  "pkg": "ovh",
  "mod": "index/vRACPublicCloudAttachment",
  "fqn": "pulumi_ovh",
  "classes": {
   "ovh:index/vRACPublicCloudAttachment:VRACPublicCloudAttachment": "VRACPublicCloudAttachment"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ovh",
  "token": "pulumi:providers:ovh",
  "fqn": "pulumi_ovh",
  "class": "Provider"
 }
]
"""
)
