# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetMeSSHKeysResult',
    'AwaitableGetMeSSHKeysResult',
    'get_me_ssh_keys',
]

@pulumi.output_type
class GetMeSSHKeysResult:
    """
    A collection of values returned by getMeSSHKeys.
    """
    def __init__(__self__, id=None, names=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if names and not isinstance(names, list):
            raise TypeError("Expected argument 'names' to be a list")
        pulumi.set(__self__, "names", names)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def names(self) -> Sequence[str]:
        """
        The list of the names of all the SSH keys.
        """
        return pulumi.get(self, "names")


class AwaitableGetMeSSHKeysResult(GetMeSSHKeysResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMeSSHKeysResult(
            id=self.id,
            names=self.names)


def get_me_ssh_keys(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMeSSHKeysResult:
    """
    Use this data source to retrieve list of names of the account's SSH keys.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_ovh as ovh

    mykeys = ovh.get_me_ssh_keys()
    ```
    """
    __args__ = dict()
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('ovh:index/getMeSSHKeys:getMeSSHKeys', __args__, opts=opts, typ=GetMeSSHKeysResult).value

    return AwaitableGetMeSSHKeysResult(
        id=__ret__.id,
        names=__ret__.names)
