# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['IPReverseArgs', 'IPReverse']

@pulumi.input_type
class IPReverseArgs:
    def __init__(__self__, *,
                 ip: pulumi.Input[str],
                 reverse: pulumi.Input[str],
                 ipreverse: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a IPReverse resource.
        :param pulumi.Input[str] ip: The IP block to which the IP belongs
        :param pulumi.Input[str] reverse: The value of the reverse
        :param pulumi.Input[str] ipreverse: The IP to set the reverse of, default to `ip` if `ip` is a /32 (IPv4) or a /128 (IPv6)
        """
        pulumi.set(__self__, "ip", ip)
        pulumi.set(__self__, "reverse", reverse)
        if ipreverse is not None:
            pulumi.set(__self__, "ipreverse", ipreverse)

    @property
    @pulumi.getter
    def ip(self) -> pulumi.Input[str]:
        """
        The IP block to which the IP belongs
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: pulumi.Input[str]):
        pulumi.set(self, "ip", value)

    @property
    @pulumi.getter
    def reverse(self) -> pulumi.Input[str]:
        """
        The value of the reverse
        """
        return pulumi.get(self, "reverse")

    @reverse.setter
    def reverse(self, value: pulumi.Input[str]):
        pulumi.set(self, "reverse", value)

    @property
    @pulumi.getter
    def ipreverse(self) -> Optional[pulumi.Input[str]]:
        """
        The IP to set the reverse of, default to `ip` if `ip` is a /32 (IPv4) or a /128 (IPv6)
        """
        return pulumi.get(self, "ipreverse")

    @ipreverse.setter
    def ipreverse(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "ipreverse", value)


@pulumi.input_type
class _IPReverseState:
    def __init__(__self__, *,
                 ip: Optional[pulumi.Input[str]] = None,
                 ipreverse: Optional[pulumi.Input[str]] = None,
                 reverse: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering IPReverse resources.
        :param pulumi.Input[str] ip: The IP block to which the IP belongs
        :param pulumi.Input[str] ipreverse: The IP to set the reverse of, default to `ip` if `ip` is a /32 (IPv4) or a /128 (IPv6)
        :param pulumi.Input[str] reverse: The value of the reverse
        """
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if ipreverse is not None:
            pulumi.set(__self__, "ipreverse", ipreverse)
        if reverse is not None:
            pulumi.set(__self__, "reverse", reverse)

    @property
    @pulumi.getter
    def ip(self) -> Optional[pulumi.Input[str]]:
        """
        The IP block to which the IP belongs
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "ip", value)

    @property
    @pulumi.getter
    def ipreverse(self) -> Optional[pulumi.Input[str]]:
        """
        The IP to set the reverse of, default to `ip` if `ip` is a /32 (IPv4) or a /128 (IPv6)
        """
        return pulumi.get(self, "ipreverse")

    @ipreverse.setter
    def ipreverse(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "ipreverse", value)

    @property
    @pulumi.getter
    def reverse(self) -> Optional[pulumi.Input[str]]:
        """
        The value of the reverse
        """
        return pulumi.get(self, "reverse")

    @reverse.setter
    def reverse(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "reverse", value)


class IPReverse(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 ip: Optional[pulumi.Input[str]] = None,
                 ipreverse: Optional[pulumi.Input[str]] = None,
                 reverse: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Provides a OVH IP reverse.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_ovh as ovh

        # Set the reverse of an IP
        test = ovh.IPReverse("test",
            ip="192.0.2.0/24",
            ipreverse="192.0.2.1",
            reverse="example.com")
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] ip: The IP block to which the IP belongs
        :param pulumi.Input[str] ipreverse: The IP to set the reverse of, default to `ip` if `ip` is a /32 (IPv4) or a /128 (IPv6)
        :param pulumi.Input[str] reverse: The value of the reverse
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IPReverseArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provides a OVH IP reverse.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_ovh as ovh

        # Set the reverse of an IP
        test = ovh.IPReverse("test",
            ip="192.0.2.0/24",
            ipreverse="192.0.2.1",
            reverse="example.com")
        ```

        :param str resource_name: The name of the resource.
        :param IPReverseArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IPReverseArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 ip: Optional[pulumi.Input[str]] = None,
                 ipreverse: Optional[pulumi.Input[str]] = None,
                 reverse: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IPReverseArgs.__new__(IPReverseArgs)

            if ip is None and not opts.urn:
                raise TypeError("Missing required property 'ip'")
            __props__.__dict__["ip"] = ip
            __props__.__dict__["ipreverse"] = ipreverse
            if reverse is None and not opts.urn:
                raise TypeError("Missing required property 'reverse'")
            __props__.__dict__["reverse"] = reverse
        super(IPReverse, __self__).__init__(
            'ovh:index/iPReverse:IPReverse',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            ip: Optional[pulumi.Input[str]] = None,
            ipreverse: Optional[pulumi.Input[str]] = None,
            reverse: Optional[pulumi.Input[str]] = None) -> 'IPReverse':
        """
        Get an existing IPReverse resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] ip: The IP block to which the IP belongs
        :param pulumi.Input[str] ipreverse: The IP to set the reverse of, default to `ip` if `ip` is a /32 (IPv4) or a /128 (IPv6)
        :param pulumi.Input[str] reverse: The value of the reverse
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IPReverseState.__new__(_IPReverseState)

        __props__.__dict__["ip"] = ip
        __props__.__dict__["ipreverse"] = ipreverse
        __props__.__dict__["reverse"] = reverse
        return IPReverse(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def ip(self) -> pulumi.Output[str]:
        """
        The IP block to which the IP belongs
        """
        return pulumi.get(self, "ip")

    @property
    @pulumi.getter
    def ipreverse(self) -> pulumi.Output[Optional[str]]:
        """
        The IP to set the reverse of, default to `ip` if `ip` is a /32 (IPv4) or a /128 (IPv6)
        """
        return pulumi.get(self, "ipreverse")

    @property
    @pulumi.getter
    def reverse(self) -> pulumi.Output[str]:
        """
        The value of the reverse
        """
        return pulumi.get(self, "reverse")

