// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to get the list of compatible netboots for a dedicated server associated with your OVH Account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@pulumi/ovh";
 *
 * const netboots = pulumi.output(ovh.getDedicatedServerBoots({
 *     bootType: "harddisk",
 *     serviceName: "myserver",
 * }));
 * ```
 */
export function getDedicatedServerBoots(args: GetDedicatedServerBootsArgs, opts?: pulumi.InvokeOptions): Promise<GetDedicatedServerBootsResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ovh:index/getDedicatedServerBoots:getDedicatedServerBoots", {
        "bootType": args.bootType,
        "kernel": args.kernel,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getDedicatedServerBoots.
 */
export interface GetDedicatedServerBootsArgs {
    /**
     * Filter the value of bootType property (harddisk, rescue, ipxeCustomerScript, internal, network)
     */
    bootType?: string;
    kernel?: string;
    /**
     * The internal name of your dedicated server.
     */
    serviceName: string;
}

/**
 * A collection of values returned by getDedicatedServerBoots.
 */
export interface GetDedicatedServerBootsResult {
    readonly bootType?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly kernel?: string;
    /**
     * The list of dedicated server netboots.
     */
    readonly results: number[];
    readonly serviceName: string;
}

export function getDedicatedServerBootsOutput(args: GetDedicatedServerBootsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDedicatedServerBootsResult> {
    return pulumi.output(args).apply(a => getDedicatedServerBoots(a, opts))
}

/**
 * A collection of arguments for invoking getDedicatedServerBoots.
 */
export interface GetDedicatedServerBootsOutputArgs {
    /**
     * Filter the value of bootType property (harddisk, rescue, ipxeCustomerScript, internal, network)
     */
    bootType?: pulumi.Input<string>;
    kernel?: pulumi.Input<string>;
    /**
     * The internal name of your dedicated server.
     */
    serviceName: pulumi.Input<string>;
}
