// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information about an SSH key.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@pulumi/ovh";
 *
 * const mykey = pulumi.output(ovh.getMeSSHKey({
 *     keyName: "mykey",
 * }));
 * ```
 */
export function getMeSSHKey(args: GetMeSSHKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetMeSSHKeyResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ovh:index/getMeSSHKey:getMeSSHKey", {
        "keyName": args.keyName,
    }, opts);
}

/**
 * A collection of arguments for invoking getMeSSHKey.
 */
export interface GetMeSSHKeyArgs {
    /**
     * The name of the SSH key.
     */
    keyName: string;
}

/**
 * A collection of values returned by getMeSSHKey.
 */
export interface GetMeSSHKeyResult {
    /**
     * True when this public SSH key is used for rescue mode and reinstallations.
     */
    readonly default: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The content of the public key.
     * E.g.: "ssh-ed25519 AAAAC3..."
     */
    readonly key: string;
    /**
     * See Argument Reference above.
     */
    readonly keyName: string;
}

export function getMeSSHKeyOutput(args: GetMeSSHKeyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMeSSHKeyResult> {
    return pulumi.output(args).apply(a => getMeSSHKey(a, opts))
}

/**
 * A collection of arguments for invoking getMeSSHKey.
 */
export interface GetMeSSHKeyOutputArgs {
    /**
     * The name of the SSH key.
     */
    keyName: pulumi.Input<string>;
}
