// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information about a credit card
 * payment mean associated with an OVH account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@pulumi/ovh";
 *
 * const cc = pulumi.output(ovh.getMePaymentMeanCreditCard({
 *     useDefault: true,
 * }));
 * ```
 */
export function getMePaymentMeanCreditCard(args?: GetMePaymentMeanCreditCardArgs, opts?: pulumi.InvokeOptions): Promise<GetMePaymentMeanCreditCardResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ovh:index/getMePaymentMeanCreditCard:getMePaymentMeanCreditCard", {
        "descriptionRegexp": args.descriptionRegexp,
        "states": args.states,
        "useDefault": args.useDefault,
        "useLastToExpire": args.useLastToExpire,
    }, opts);
}

/**
 * A collection of arguments for invoking getMePaymentMeanCreditCard.
 */
export interface GetMePaymentMeanCreditCardArgs {
    /**
     * a regexp used to filter credit cards 
     * on their `description` attributes.
     */
    descriptionRegexp?: string;
    /**
     * Filter credit cards on their `state` attribute.
     * Can be "expired", "valid", "tooManyFailures"
     */
    states?: string[];
    /**
     * Retrieve credit card marked as default payment mean.
     */
    useDefault?: boolean;
    /**
     * Retrieve the credit card that will be the last
     * to expire according to its expiration date.
     */
    useLastToExpire?: boolean;
}

/**
 * A collection of values returned by getMePaymentMeanCreditCard.
 */
export interface GetMePaymentMeanCreditCardResult {
    /**
     * a boolean which tells if the retrieved credit card
     * is marked as the default payment mean
     */
    readonly default: boolean;
    /**
     * the description attribute of the credit card
     */
    readonly description: string;
    readonly descriptionRegexp?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * the state attribute of the credit card
     */
    readonly state: string;
    readonly states?: string[];
    readonly useDefault?: boolean;
    readonly useLastToExpire?: boolean;
}

export function getMePaymentMeanCreditCardOutput(args?: GetMePaymentMeanCreditCardOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMePaymentMeanCreditCardResult> {
    return pulumi.output(args).apply(a => getMePaymentMeanCreditCard(a, opts))
}

/**
 * A collection of arguments for invoking getMePaymentMeanCreditCard.
 */
export interface GetMePaymentMeanCreditCardOutputArgs {
    /**
     * a regexp used to filter credit cards 
     * on their `description` attributes.
     */
    descriptionRegexp?: pulumi.Input<string>;
    /**
     * Filter credit cards on their `state` attribute.
     * Can be "expired", "valid", "tooManyFailures"
     */
    states?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Retrieve credit card marked as default payment mean.
     */
    useDefault?: pulumi.Input<boolean>;
    /**
     * Retrieve the credit card that will be the last
     * to expire according to its expiration date.
     */
    useLastToExpire?: pulumi.Input<boolean>;
}
