// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Attach a Dedicated Server Network Interface to a VRack.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@pulumi/ovh";
 *
 * const vdsi = new ovh.VRACDedicatedServerInterface("vdsi", {
 *     interfaceId: "67890",
 *     vrackId: "12345",
 * });
 * ```
 */
export class VRACDedicatedServerInterface extends pulumi.CustomResource {
    /**
     * Get an existing VRACDedicatedServerInterface resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VRACDedicatedServerInterfaceState, opts?: pulumi.CustomResourceOptions): VRACDedicatedServerInterface {
        return new VRACDedicatedServerInterface(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ovh:index/vRACDedicatedServerInterface:VRACDedicatedServerInterface';

    /**
     * Returns true if the given object is an instance of VRACDedicatedServerInterface.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VRACDedicatedServerInterface {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VRACDedicatedServerInterface.__pulumiType;
    }

    /**
     * The id of dedicated server network interface.
     */
    public readonly interfaceId!: pulumi.Output<string>;
    /**
     * The id of the vrack.
     */
    public readonly vrackId!: pulumi.Output<string>;

    /**
     * Create a VRACDedicatedServerInterface resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VRACDedicatedServerInterfaceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VRACDedicatedServerInterfaceArgs | VRACDedicatedServerInterfaceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VRACDedicatedServerInterfaceState | undefined;
            resourceInputs["interfaceId"] = state ? state.interfaceId : undefined;
            resourceInputs["vrackId"] = state ? state.vrackId : undefined;
        } else {
            const args = argsOrState as VRACDedicatedServerInterfaceArgs | undefined;
            if ((!args || args.interfaceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'interfaceId'");
            }
            if ((!args || args.vrackId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vrackId'");
            }
            resourceInputs["interfaceId"] = args ? args.interfaceId : undefined;
            resourceInputs["vrackId"] = args ? args.vrackId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VRACDedicatedServerInterface.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VRACDedicatedServerInterface resources.
 */
export interface VRACDedicatedServerInterfaceState {
    /**
     * The id of dedicated server network interface.
     */
    interfaceId?: pulumi.Input<string>;
    /**
     * The id of the vrack.
     */
    vrackId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a VRACDedicatedServerInterface resource.
 */
export interface VRACDedicatedServerInterfaceArgs {
    /**
     * The id of dedicated server network interface.
     */
    interfaceId: pulumi.Input<string>;
    /**
     * The id of the vrack.
     */
    vrackId: pulumi.Input<string>;
}
